pipeline {
    agent any

    environment {
        DOTNET_ROOT = "/usr/share/dotnet"
        PROJECT_PATH = "ApiTask/ApiTask/ApiTask.csproj"
        DOCKER_CONTEXT = "ApisTask" // onde está o Dockerfile, se aplicável
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Restore') {
            steps {
                sh "dotnet restore $PROJECT_PATH"
            }
        }

        stage('Build') {
            steps {
                sh "dotnet build $PROJECT_PATH --configuration Release"
            }
        }

        stage('Docker Build') {
            steps {
                sh "docker build -t minha-api:latest $DOCKER_CONTEXT"
            }
        }

        stage('Run Container') {
            steps {
                sh "docker rm -f minha-api || true"
                sh "docker run -d --name minha-api -p 8081:80 minha-api:latest"
            }
        }
    }

    post {
        success {
            echo '✅ Build e deploy concluídos com sucesso!'
        }
        failure {
            echo '❌ Algo deu errado no pipeline.'
        }
    }
}