pipeline {
    agent any

    environment {
        DOTNET_ROOT = "/usr/share/dotnet"
        PROJECT_PATH = "ApiTask/ApiTask.csproj"
        DOCKER_CONTEXT = "ApiTask"
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ManoelCod/ApiTask.git',
                    branch: 'main'
                // Para repositório privado, adicione:
                // credentialsId: 'id-da-sua-credencial'
            }
        }

        stage('Restore') {
            steps {
                sh "dotnet restore \"$PROJECT_PATH\""
            }
        }

        stage('Build') {
            steps {
                sh "dotnet build \"$PROJECT_PATH\" --configuration Release"
            }
        }
    }

    post {
        success {
            echo '✅ Build e deploy concluídos com sucesso!'
        }
        failure {
            echo '❌ Algo deu errado no pipeline.'
        }
    }
}